config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users
  resources :departments
  resources :categories

  resources :jobs do
    member do 
      get :remove_document
      patch :mark_as_filled
    end
  end

  root :to => 'jobs#index'
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :department
	has_one :category

	validates :title, presence: true
	validates :category_id, presence: true
	validates :department, presence: true
	validates :start_salary, presence: true
	validates :end_salary, presence: true
	validates :description, presence: true
	validates :start_grade, presence: true
	validates :end_grade, presence: true
	validates :publish_date, presence: true
	validates :ends_on, presence: true

	validates_date :publish_date, before: :ends_on, on_or_after: lambda { Date.today }
	validates_date :ends_on, after: :publish_date
	validates_date :date_filled, after: :ends_on, after: :publish_date, allow_blank: true

	mount_uploaders :documents, DocumentUploader # Tells rails to use this uploader for this model.

	scope :active, -> { where('ends_on > ?', Date.today).where(filled: false).where('publish_date <= ?', Date.today) }
	scope :by_category, ->(category_id) { where(category_id: category_id) }
	scope :by_title, ->(title) { where("title ILIKE ?", "%#{title}%") }
	scope :by_department, ->(department) { where(department_id: department) }
	scope :by_start_and_end_salary, ->(start_salary, end_salary) { where(start_salary: start_salary, end_salary: end_salary) }
	scope :by_filled, -> { where(filled: true) }

	def days_left
		left = (ends_on - publish_date).to_i
		if left > 0
			left
		elsif left == 0
			'Last Day'
		elsif left < 0
			'Closed'
		end
	end

	def active?
		ends_on > Date.today
	end

	def filled_status?
		if filled?
			"Filled"
		else 
			"Not Filled"
		end
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  include ApplicationHelper

  before_action :set_job, only: [:show, :edit, :update, :destroy, :remove_document, :mark_as_filled]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :remove_document, :mark_as_filled]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    # @active_jobs = Job.active
    @categories = Category.all
    @departments = Department.all
    @pagy, @active_jobs = pagy(Job.all, items: 10) #change this to active after testing
    @active_jobs_count = Job.all.count #change this to active after testing
    @active_categories = @active_jobs.pluck(:category_id).uniq.map { |id| Category.find(id) }
    @active_jobs_salaries = @active_jobs.pluck(:start_salary, :end_salary)
    @active_departments = @active_jobs.pluck(:department_id).uniq.map { |id| Department.find(id) }
    @filled_jobs = Job.by_filled
    @not_filled_jobs_count = Job.all.count - @filled_jobs.count

    # Filter 
    job_filter

    # Search 
    @active_jobs = @active_jobs.by_title(params[:search][:title]) if params[:search].present?
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit

  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def job_filter
    if !admin? or !editor?
      @active_jobs = @active_jobs.by_category(params[:category]) if params[:category].present?
      @active_jobs = @active_jobs.by_department(params[:department]) if params[:department].present?
      @active_jobs = @active_jobs.by_start_and_end_salary(params[:start_salary], params[:end_salary]) if params[:start_salary].present? and params[:end_salary].present?
    else
      @jobs = @jobs.by_category(params[:category]) if params[:category].present?
      @jobs = @jobs.by_department(params[:department]) if params[:department].present?    
    end
  end

  # Remove Document from job
  def remove_document
    @document_to_remove = params[:document].to_i

    remain_documents = @job.documents 
    deleted_documents = remain_documents.delete_at(@document_to_remove) 
    @job.documents = remain_documents

    respond_to do |format|
      if @job.save
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # Mark job as filled
  def mark_as_filled
    respond_to do |format|
      @job_params = params[:job]
      @date = Date.new(@job_params["date_filled(1i)"].to_i, @job_params["date_filled(2i)"].to_i, @job_params["date_filled(3i)"].to_i)
      @job.update_attribute(:date_filled, @date) and @job.update_attribute(:filled, true)

      if @job.save(:validate => true)
        format.html { redirect_to @job, notice: "Marked as filled" }
        format.json { head :no_content }
      else
        format.html { render :show, alert: "Date filled can't be before deadline or publish_date" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(
        :title, 
        :department_id,
        :category_id, 
        :description, 
        :start_salary, 
        :end_salary, 
        :start_grade, 
        :end_grade, 
        :allowance, 
        :publish_date, 
        :ends_on, 
        :filled, 
        :date_filled,
        :documents => [])
    end
end

app/helpers/jobs_helper.rb
module JobsHelper

	def active_job_categories_by_id(category_id)
		Job.all.by_category(category_id) #cahnge to active
	end

	def format_salary(job)
		"$#{job.start_salary} - $#{job.end_salary}"
	end

	def format_grade(job)
		"#{job.start_grade} - #{job.end_grade}"
	end

	# Format for catigories, to show the count if the count is more than 0
	# if not it removes the ()
	def format_count(count)
		if count != 0
			"(#{count})"
		else
			""
		end
	end

end

app/views/jobs/_dealine_notice.html.erb
<div class="alert alert-info alert-dismissible fade show" role="alert">
	<i class="bx bx-error"></i>
	<strong>This Job Listing Has Expired</strong>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	<span aria-hidden="true">×</span>
	</button>
	<p>To Make this job visable again, you can change the dealine date.</p>
	<p class="font-weight-bold">Has this job been filled?</p>

	<button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModal">
	 Mark As Filled
	</button>
</div><!--/.alert-->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Mark Job As Filled</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
				<%= simple_form_for(@job, 
					:url => mark_as_filled_job_url(), 
					:method => :patch) do |f| %>
					
					<%= f.input :date_filled, 
						:label => "Date job was filled" %>

					<%= f.submit "Mark As Filled", 
						:class => "btn btn-primary"  %>
				<% end %>
      </div>
    </div>
  </div><!--/.modal-dialog-->
</div> <!--/.modal-->

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, 
                :input_html => { :placeholder => "Office Attendant/ Driver" } %>

    <%= f.input :category_id, 
                :collection => Category.all,
                :prompt => "Please select a category" %>

    <%= f.association :department,
                      :prompt => "Please select a department" %>

    <%= f.input :description,
                :input_html => { :class => "tinymce", :rows => 20, :cols => 25 } %>

    <%= f.input :start_salary,
                :as => :integer,
                :input_html => { min: 0 } %>

    <%= f.input :end_salary,
                :as => :integer,
                :input_html => { min: 0 } %>

    <%= f.input :start_grade %>

    <%= f.input :end_grade %>

    <%= f.input :allowance,
                :input_html => { :class => "tinymce", :rows => 20, :cols => 25 } %>

    <%= f.input :publish_date,
                :start_year => Date.today.year,
                :start_month => Date.today.month,
                :start_date => Date.today.day,
                :hint => "Date when the job will be visable to everyone" %>

    <%= f.input :ends_on,
                :label => "Deadline Date",
                :start_year => Date.today.year %>
    
    <h5 class="mb-4">Add Additional Files </h5>
    <% if @job.documents.present? %>
      <% @job.documents.each do |document| %>
        <div class="">
          <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABN0lEQVRIS+2WzU3DQBCF37O5UwK5+oSpIO4ASnBaQIQb/uEaeiAlQAdpASmSr0kHNBAPs5sfRSTybjaylEN8tWe+N7Mzb030/LDn/DgAvDRlRsinggfdcE4nST1yCTwAjJtioUF3rsD1ezfkGEDcyUWV01TphAQBJsk7x81b7gMJBhjtPpCzAD6QswH/IaZ9+2cYBOgagivAuSKX1SK7UPMyZSxPRrqs+CU3aCHyHAGLSK1ihVZthbNtaSdVsN7YYiZgFUEy9ZBM7fE+Fj4oJReI+hZ1ozEMBrw2RSXEIwXfFgCkMZgaQGuVy1BnvQoGaAXW/DRJvW0R0dYU/ti2AeX+yZ/UIufIHPngIgC/Kuw2RL3GLLWCQacXba7MqX7keavt0i112vKPpN6N7ObsArV6hvX+V/EHnTypGdyYNXYAAAAASUVORK5CYII="/>
          <%= document.identifier%>
          <%= link_to ' | Remove', remove_document_job_path(:document => document.index) %>
        </div>

        <%= hidden_field :job, :documents, multiple: true, value: document.identifier %>
      <% end %>
    <% end %>

    <%= f.file_field :documents,
                     :label => 'Add Attachments',
                     :multiple => true,
                     :class => "mb-4",
                     :accept => ".pdf, .doc, .docx" %>

    <%= tinymce %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary mb-4 mt-5" %>
  </div>
<% end %>

app/views/jobs/_jobs.html.erb
<div id="job-list">
  <% @active_jobs.each do |job| %>
    <div class="card card-row shadow-light-lg mb-3 lift lift-lg">
      <div class="card-body">

        <%if admin? or editor?  %>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>

          <% if job.filled? %>
            <span class="badge badge-lg badge-success-soft float-right ml-3">
              <span class="text-uppercase font-weight-bold"><%= job.filled_status? %> </span>
            </span>
          <% else %>
            <span class="badge badge-lg badge-danger-soft float-right ml-3">
              <span class="text-uppercase font-weight-bold"><%= job.filled_status? %> </span>
            </span>
          <% end %>
        <% end %>

        <span class="badge badge-lg badge-primary-soft float-right">
          <span class="text-uppercase font-weight-bold"><%= find_category(job.category_id).name %> </span>
        </span>

        <h3 class="font-weight-bold"><%= link_to job.title, job %></h3>

        <p class="mb-0 small text-muted">
          Department: <%= job.department.name %> | Grade: <%= job.start_grade %> - <%= job.end_grade %>
        </p>

        <div class="jobs_days_left card-meta p-0 pt-2">
          <hr class="card-meta-divider mb-1">
          <i class="bx bx-time"></i>
          <p class="small text-muted font-weight-bold mr-2 mb-0 pl-2">Days left: <%= job.days_left %></p>
          <p class="ml-auto small text-muted font-weight-bold pt-2">Deadline: <%= job.ends_on %></p>
          <p class="ml-auto small text-muted font-weight-bold pt-2">Salary: $<%= job.start_salary%> - $<%= job.end_salary %></p>
        </div><!--/.jobs_days_left-->

      </div><!--/.card-body-->
    </div><!--/.card-->
  <% end %>
</div><!--/.jobs-->

app/views/jobs/_side_filter.html.erb
<div class="card card-bleed border-bottom border-bottom-md-0 shadow-light-lg">
  <div class="collapse d-md-block" id="sidenavCollapse">
    <div class="card-body">

      <h6 class="font-weight-bold text-uppercase mb-3">
        Browse Categories
      </h6>
      
      <ul class="card-list list text-gray-700 mb-6">
        <li class="list-item">
          <%= link_to 'All', root_path %>
          <% if !admin? or !editor? %>
            <%= format_count(@active_jobs_count) %>
          <% else %>
            <%= format_count(@jobs.count) %>
          <% end %>
        </li>

        <% if admin? or editor? %>
          <li class="list-item">
            <%= link_to 'Active Jobs' %>
            <%= format_count(@active_jobs_count) %>
          </li>

          <li class="list-item">
            <%= link_to 'Filled Jobs' %>
            <%= format_count(@filled_jobs.count) %>
          </li>

          <li class="list-item">
            <%= link_to 'Not Filled Jobs' %>
            <%= format_count(@not_filled_jobs_count) %>
          </li>
        <% end %>

        <% if !admin? and !editor? %>
          <% @active_categories.each do |category| %>
            <li class="list-item">
              <%= link_to jobs_path(:category => category), class:"list-link text-reset" do %>
                <%= category.name %>
                <%= format_count(@active_jobs_category_amount = active_job_categories_by_id(category.id).count) %>
              <% end %> 
            </li>
          <% end %>
        <% else %>
          <% @categories.each do |category| %>
            <li class="list-item">
              <%= link_to category.name  %>
            </li>
          <% end %>
        <% end %>
      </ul>
    
      <h6 class="font-weight-bold text-uppercase mb-3">
        Departments
      </h6>

      <ul class="card-list list text-gray-700 mb-6">
        <% if !admin? and !editor? %>
          <% @active_departments.each do |department| %>
            <li class="list-item">
              <%= link_to department.name, jobs_path(:department => department), class:"list-link text-reset" %>
            </li>
          <% end %>
        <% else %>
          <% @departments.each do |department| %>
            <li class="list-item">
              <%= link_to department.name, jobs_path(:department => department), class:"list-link text-reset" %>
            </li>
          <% end %>
        <% end %>
      </ul>
      
      <% if !admin? and !editor? %>
        <h6 class="font-weight-bold text-uppercase mb-3">
          Salary Range
        </h6>

        <ul class="card-list list text-gray-700 mb-6">
          <% @active_jobs_salaries.each do |salary| %>
            <li class="list-item">
              <%= link_to "$#{salary[0]} - $#{salary[1]}",
                  jobs_path(:start_salary => salary[0],
                            :end_salary => salary[1]
                            )  %>
            </li>
          <% end %>
        </ul>
      <% end %>

    </div> <!--/.card-body-->
  </div><!--/.collapse-->
</div><!--/.card-->

app/views/jobs/edit.html.erb
<div class="pt-md-8">
	<%= render 'layouts/back', :path => @job, :text => "Back" %>

	<h1 class="display-4 mb-4 mt-4">Edit Job</h1>

	<%= render 'form', job: @job %>
</div>

app/views/jobs/index.html.erb
<div class="pt-md-8">
  <%= render 'layouts/alerts' %>

  <!-- Search  -->
  <div class="search py-6">
    <div class="row">
      <div class="col-12">
        <%= simple_form_for :search, url: root_path, method: "GET", html: { class: 'rounded shadow' } do |f| %>
          <div class="input-group input-group-lg">
            <div class="input-group-prepend">
              <span class="input-group-text border-0 pr-1">
                <i class="fe fe-search"></i>
              </span>
            </div>

            <%= f.input :title, 
                        :input_html => { class:"border-0 px-1", placeholder:"Search for a job...", arialabel: "Search for a job..." },
                        :label => false,
                        :required => false,
                        :wrapper_html => { class:"mb-0 custom-form-group" } %>

            <div class="input-group-append">
              <span class="input-group-text border-0 py-0 pl-1 pr-3">
                <%= f.submit "Search", class: "btn btn-sm btn-primary" %>
              </span>
            </div>
          </div> <!--/.input-group-->
        <% end %>
      </div><!--/.col-->
    </div> <!-- / .row -->
  </div> <!--/.search-->

  <div class="row">
    <div class="col-12 col-md-3">
      <%= render 'side_filter' %>
    </div><!--/.col-->

    <div class="col-12 col-md-9">
      <% if admin? or editor? %>
        <%= link_to 'New Job', new_job_path, class: "btn btn-sm btn-primary mb-4" %>
      <% end %>
      
      <% if @active_jobs.present? %>
        <%= render 'jobs' %>
      <% else %>
        <div class="col-12 col-md-10">
          <h3 class="text-muted text-center font-weight-bold">Nothing Found</h3>
          <%= image_tag("no-job.svg", :alt => "no-job-svg", :class => "img-fluid") %>
        </div>
      <% end %>

      <%= pagy_bootstrap_nav(@pagy).html_safe %>
    </div><!--/.col-->
  </div><!--/.row-->

</div>

app/views/jobs/new.html.erb
<div class="pt-md-8">
	<%= render 'layouts/back', :path => jobs_path, :text => "Back" %>

	<h1>New Job</h1>

	<%= render 'form', job: @job %>
</div>

app/views/jobs/show.html.erb
<div class="pt-8 pt-md-8">
  <%= render 'layouts/alerts' %>

  <div class="">
    <% if !@job.active? %>
      <%= render 'dealine_notice' %>
    <% end %>

    <div class="row align-items-center">
      <div class="col-12 col-md">
        <%= render 'layouts/back', :path => jobs_path, :text => "Back" %>
        
        <!-- Heading -->
        <% if admin? or editor? %>
          <h3 class="mt-4">
            <%= link_to 'Edit', edit_job_path(@job), class:"btn-sm btn-secondary" %>
          </h3>
        <% end %>

        <h1 class="display-4 mb-2 mt-4">
          <%= @job.title %>
        </h1>
        <p class="font-size-lg text-gray-700 mb-5 mb-md-0">
          <%= @job.department.name %> · <%= find_category(@job.category_id).name %>
        </p>

        <p class="font-size-lg text-gray-700 mb-5 mb-md-0">
          Grade: <%= format_grade(@job) %>
        </p>
      </div><!--/.col-->

      <div class="col-auto">
        <p class="font-size-lg text-gray-700 mb-3 text-align-right font-weight-bold">
          Salary: <%= format_salary(@job) %>
        </p>
        <span class="badge badge-lg badge-success">
          Days Left:
          <span class="h6 text-uppercase font-weight-bold"><%= @job.days_left %></span>
        </span>

        <span class="badge badge-lg badge-danger-soft">
          Deadline Date: 
          <span class="h6 text-uppercase font-weight-bold"><%= @job.ends_on %></span>
        </span>
      </div>
    </div><!--/.row-->

    <div class="row">
      <div class="col-12">
        <!-- Divider -->
        <hr class="my-6 my-md-8 border-gray-300">
      </div>
    </div><!--/.row-->

    <div class="row">
      <div class="col-12 col-md-8">
        <!-- About the Job -->
        <%= sanitize(@job.description) %>

        <!-- Documents -->
        <% if @job.documents.present? %>
          <h3>Additional Documents</h3>
          <% @job.documents.each do |document| %>
            <p>
              <%= link_to document.url do %>
                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABN0lEQVRIS+2WzU3DQBCF37O5UwK5+oSpIO4ASnBaQIQb/uEaeiAlQAdpASmSr0kHNBAPs5sfRSTybjaylEN8tWe+N7Mzb030/LDn/DgAvDRlRsinggfdcE4nST1yCTwAjJtioUF3rsD1ezfkGEDcyUWV01TphAQBJsk7x81b7gMJBhjtPpCzAD6QswH/IaZ9+2cYBOgagivAuSKX1SK7UPMyZSxPRrqs+CU3aCHyHAGLSK1ihVZthbNtaSdVsN7YYiZgFUEy9ZBM7fE+Fj4oJReI+hZ1ozEMBrw2RSXEIwXfFgCkMZgaQGuVy1BnvQoGaAXW/DRJvW0R0dYU/ti2AeX+yZ/UIufIHPngIgC/Kuw2RL3GLLWCQacXba7MqX7keavt0i112vKPpN6N7ObsArV6hvX+V/EHnTypGdyYNXYAAAAASUVORK5CYII="/>
                Download Document
              <% end %>
            </p>
          <% end %>
        <% end %>

      </div><!--/.col-->
      
      <!-- Side Helper -->
      <div class="col-12 col-md-4">
        <div class="card shadow-light-lg mb-5">
          <div class="card-body">
            <h4>
              Need help?
            </h4>
            <p class="font-size-sm text-gray-800 mb-5">
              Not sure exactly what we’re looking for or just want clarification? We’d be happy to chat with you and clear things up for you. 
            </p>
            <h6 class="font-weight-bold text-uppercase text-gray-700 mb-2">
              Call anytime
            </h6>
            <p class="font-size-sm mb-5">
              (664) 000-0000
            </p>
            <h6 class="font-weight-bold text-uppercase text-gray-700 mb-2">
              Email us
            </h6>
            <p class="font-size-sm mb-0">
              support@gov.ms
            </p>
          </div><!--/.card-body-->
        </div><!--/.card-->
      </div> <!--/.col-->

    </div><!--/.row-->
  </div><!--/.container-->
</div>