config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users
  resources :departments
  resources :categories

  resources :jobs do
    member do 
      get :remove_document
      patch :mark_as_filled
    end
  end

  root :to => 'jobs#index'
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :jobs

	validates :name, presence: true
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :show, :new, :destroy]


  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all.order('id ASC')
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to departments_path, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to departments_path, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper

end

app/views/departments/_form.html.erb
<%= simple_form_for(@department) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<div class="pt-md-8">
	<%= render 'layouts/back', :path => departments_path, :text => "Back" %>

	<h1 class="display-4 mb-4 mt-4">Editing Department</h1>

	<%= render 'form', department: @department %>
</div>

app/views/departments/index.html.erb
<div class="pt-md-8">
  <%= render 'layouts/alerts' %>

  <h1 class="display-4 mb-4 mt-4">Departments</h1>
  <%= link_to 'New Department', new_department_path, class: "btn btn-sm btn-primary" %>

  <div class="table-responsive shadow mt-4">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% @departments.each do |department| %>
          <tr>
            <td><%= department.id %></td>
            <td><%= department.name %></td>
            <td><%= link_to 'Edit', edit_department_path(department) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><!--/.table-responsive-->
  
</div>

app/views/departments/new.html.erb
<div class="pt-md-8">
	<%= render 'layouts/back', :path => categories_path, :text => "Back" %>

	<h1 class="display-4 mb-4 mt-4">New Department</h1>

	<%= render 'form', department: @department %>
</div>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>