config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users
  resources :departments
  resources :categories

  resources :jobs do
    member do 
      get :remove_document
      patch :mark_as_filled
    end
  end

  root :to => 'jobs#index'
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :show, :new, :destroy]


  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order('id ASC')
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper

	def find_category(id)
		Category.find(id)
	end
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="pt-md-8">
	<%= render 'layouts/back', :path => categories_path, :text => "Back" %>

	<h1 class="display-4 mb-4 mt-4">Editing Category</h1>

	<%= render 'form', category: @category %>
</div>

app/views/categories/index.html.erb
<div class="pt-md-8">
  <%= render 'layouts/alerts' %>

  <h1 class="display-4 mb-4 mt-4">Categories</h1>
  <%= link_to 'New Category', new_category_path, class: "btn-sm btn btn-primary" %>

  <div class="table-responsive shadow mt-4">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><!--/.table-responsive-->

</div>

app/views/categories/new.html.erb
<div class="pt-md-8">
	<%= render 'layouts/back', :path => categories_path, :text => "Back" %>

	<h1 class="display-4 mb-4 mt-4">New Category</h1>

	<%= render 'form', category: @category %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>