config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users
  resources :departments
  resources :categories

  resources :jobs do
    member do 
      get :remove_document
      patch :mark_as_filled
    end
  end

  root :to => 'jobs#index'
end

app/views/layouts/_alerts.html.erb
<% if notice.present? %>
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		<strong><%= notice %></strong> 
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">×</span>
		</button>
	</div>
<% end %>

<% if alert.present? %>
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
	<strong><%= alert %></strong> 
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">×</span>
		</button>
	</div>
<% end %>

app/views/layouts/_back.html.erb
<%= link_to path, class:"font-weight-bold font-size-sm text-decoration-none mb-3" do %>
  <i class="bx bx-arrow-back"></i>
  <%= text %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="bg-gray-200">
      <div class="container">
        <div class="row">
          <div class="col-12">
            
            <!-- Breadcrumb -->
            <ol class="breadcrumb breadcrumb-scroll">
              <li class="breadcrumb-item">
                <a href="blog.html" class="text-gray-700">
                  Jobs
                </a>
              </li>
            </ol>
          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light navbar-expand-lg mb-3 shadow">
  <%= link_to 'Jobs', root_path, class: "navbar-brand pl-4" %>
    
  <ul class="navbar-nav ml-auto">
    <% if admin? %>
      <li class="n  av-item">
        <%= link_to 'Manage Users', users_path, class: "nav-link" %>
      </li>
    <% end %>

    <% if admin? or editor? %>
      <li class="nav-item">
        <%= link_to 'Departments', departments_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to 'Categories', categories_path, class: "nav-link" %>
      </li>
      
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-danger" do  %>
          <i class="bx bx-exit font-size-16 align-middle mr-1 text-danger"></i> Log Out
        <% end %> 
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Boxicons -->
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'layouts/navigation' %>
    <div class="container">
      <div class="">
        <%= yield %>
      </div>
    </div>
  </body>
</html>